export { default as AboutView } from './AboutView';
export { default as AddNewProductView } from './AddNewProductView';
export { default as CategoriesView } from './CategoriesView';
export { default as ProductsView } from './ProductsView';
export { default as CartView } from './CartView';
export { default as NotFoundView } from './NotFoundView';
export { default as EditProductView } from './EditProductView';
export { default as SignInView } from './SignInView';
export { default as SpecificProductView } from './SpecificProductView';
